import Head from "next/head";
import { Rubik } from "next/font/google";
import { Icon } from "@iconify/react";
import styles from "@/styles/pages/blog/index.module.css";
import OfferItem from "@/components/Blog/offer.item";
import Image from "next/image";
import SimpleOfferItem from "@/components/Blog/simple.offer.item";

const rubik = Rubik({ subsets: ["latin"] });

export default function Home() {
  const elements = ["Element 1", "Element 2", "Element 3", "Element 4"];
  const articles = [
    {
      title: "Article 1",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      author: "Griffin",
      views: 1212
    },
    {
      title: "About India",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      author: "Amrit",
      views: 42
    },
    {
      title: "6+ years experiance in BDSM",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      author: "Sexslave",
      views: 708
    },
    {
      title: "Vue better than React.",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      author: "Expert",
      views: 3000
    }
  ]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div className={styles.content}>
            <div className={styles["search-wrapper"]}>
              <input
                className={styles.search}
                type="text"
                placeholder="Search"
              />
              <button className={styles["search-btn"]}>
                <Icon className={styles.icon} icon="material-symbols:search" />
              </button>
            </div>
            <div className={styles.result}>
              <div className={styles.title}>Useful</div>
              <div className={styles["offers-wrapper"]}>
                {articles.map((article, index) => (
                <OfferItem key={index} {...article}/>
                ))}
              </div>
              <div className={styles.title}>CAN HELP</div>
              <div className={styles["simple-articles-wrapper"]}>
                {elements.map((element, index) => (
                  <SimpleOfferItem key={index} title={element} />
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
