import Head from "next/head";
import { Rubik } from "next/font/google";
import { Icon } from "@iconify/react";
import styles from "@/styles/pages/blog/article/index.module.css";
import Image from "next/image";
import ActionBtn from "@/components/common/ActionBtn";

const rubik = Rubik({ subsets: ["latin"] });

export default function Article() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div className={styles.content}>
            <div className={styles["author-info"]}>
              <div className={styles["author-content"]}>
                <div className={styles["top-side"]}>
                  <div className={styles.avatar}></div>
                  <div className={styles.username}>user12403</div>
                  <div className={styles["name-surname"]}>
                    <span>John</span>
                    <span>Doe</span>
                  </div>
                  <div className={styles.email}>test@gmail.com</div>
                  <div className={styles["timestamps-wrapper"]}>
                    <div className={styles.timestamp}>
                      <div className={styles.title}>Created at</div>
                      <div className={styles.time}>13.12.2023</div>
                    </div>
                    <div className={styles.timestamp}>
                      <div className={styles.title}>Update at</div>
                      <div className={styles.time}>13.12.2023</div>
                    </div>
                  </div>
                </div>
                <div className={styles["bottom-side"]}>
                  <div className={styles.likes}>
                    <span className={styles["value"]}>12</span>
                    <Icon icon="ic:baseline-remove-red-eye" />
                  </div>
                  <div className={styles["btn-wrapper"]}>
                    <ActionBtn value={12} icon="icon-park-solid:like" />
                    <ActionBtn value={4} icon="ic:baseline-reply" />
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.article}>
              <div className={styles["article-content"]}>
                <div className={styles.breadcrumps}>
                  Blog / Article / Themetical forks in my ass
                </div>
                <h1 className={styles.title}>Themetical forks in my ass</h1>
                <div className={styles["preview-image"]}>
                  <Image
                    src="/images/callendar.png"
                    alt="Animation"
                    width={500}
                    height={300}
                  />
                </div>

                <h3 className={styles.subtitle}>HashiCorp</h3>
                <div className={styles.paragraph}>
                  In GitHub’s recent 2022 State of the Octoverse report,{" "}
                  <a className={styles.link} href="#">
                    HashiCorp Configuration Language (HCL)
                  </a>{" "}
                  was the fastest growing programming language on GitHub.
                  HashiCorp is a leading provider of Infrastructure as Code
                  (IaC) automation for cloud computing. HCL is HashiCorp’s
                  configuration language used with tools like Terraform and
                  Vault to deliver IaC capabilities in a human-readable
                  configuration file across multi-cloud and on-premises
                  environments.
                </div>
              </div>
              <div className={styles["comments-wrapper"]}>
                <div className={styles["comment-wrapper"]}>
                  <div className={styles.avatar}></div>
                  <div className={styles.comment}>
                    <div className={styles.username}>Hater</div>
                    <div className={styles.message}>Zalupa </div>
                    <div className={styles["action-wrapper"]}>
                      <ActionBtn value={12} icon="icon-park-solid:like" />
                      <ActionBtn value={4} icon="ic:baseline-reply" />
                    </div>
                  </div>
                </div>
                <div className={styles["comment-wrapper"]}>
                  <div className={styles.avatar}></div>
                  <div className={styles.comment}>
                    <div className={styles.username}>Hater</div>
                    <div className={styles["reply-on"]}>
                      <span className="message">Flask is shit</span>
                    </div>
                    <div className={styles.message}>Zalupa </div>
                    <div className={styles["action-wrapper"]}>
                      <ActionBtn value={12} icon="icon-park-solid:like" />
                      <ActionBtn value={4} icon="ic:baseline-reply" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
