import { useState } from "react";
import Head from "next/head";
import TextEditor from "@/components/Blog/text.editor";
import InputWrapper from "@/components/common/input.wrapper";
import styles from "@/styles/pages/blog/article/new.module.css";
import "react-quill/dist/quill.snow.css";
import ActionBtn from "@/components/common/ActionBtn";

export default function NewArticle() {
  const [value, setValue] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles["wrapper"]}>
          <InputWrapper title="Title" />
          <div className={styles["text-editor-wrapper"]}>
            <TextEditor />
          </div>
          <div className="btn-wrapper">
            <ActionBtn title="Public" icon={null} color="blue"/>
          </div>
        </div>
      </main>
    </>
  );
}
